### ISSUE TITLE
extract price notes

### ISSUE THREAD

**Issue by joshuago78** [gri-is/lodjob#21]

**Comment by mdlincoln** [comment]
We need to use the price notes fields in Knoedler to determine which records in the stock books are referring to the same transactions. E.g., records K-402, K-418, K-424, and K-429 are four paintings that were all purchased in 1878 for a total of 7200 marks. They all share the identical purch_note referring to them using knoedler's stock numbers `for numbers 1183-1186`

Do not attempt to actually parse the numbers themselves in these fields - this will drive you crazy, as editors used a few different conventions during this project. Rather, since editors almost always copied and pasted identical notes between records, just group by identical notes and produce some unique ID.

1. Preprocessing
    - Remove the text `/,? ?shared/` from the note field (this is a redundant bit of text editors put in whenever they also put in data about joint owners)
2. Create a unique ID for purchase events based on matching `purch_note` and a unique ID for sale events based on matching `price_note`
    - In cases where note is null, or note does not match `/[Ff]or/`, these are functionally just single-object events, so create a unique event ID for them as well.
3. Fail cases where
    - Record has a price note matching `/[Ff]or/` (suggesting it _ought_ to have 1 or more paired records) but has no paired records using the same note

Next steps (for context, not necessarily this sprint): in cases where we determine that the entry describes a purchase, rather than an inventory-taking event, we'll use purchase event IDs to create the transaction entity and describe its relationships to objects.

**Comment by melissaagill** [comment]
On hold until #45 is completed.

**Comment by mdlincoln** [comment]
This is now happening in https://github.com/gri-is/pirMerger/issues/17
