### ISSUE TITLE
sample data

### ISSUE THREAD

**Issue by joshuago78** [gri-is/lodjob#4]
- We need a sample set of data to begin working on.
- I want a csv document for Knoedler and another for Sales Catalogs.
- These tables should include all pertinent data for every row (i.e. perform all necessary joins before delivery)
- add them to the `data` directory

**Comment by mdlincoln** [comment]
For both Knoedler and Sales Catalogs, do we want to have joined all the fields from the artist/owner authorities as well? E.g., for each artist with an authority name, join the 16 fields from the artist authority we have for it?

**Comment by joshuago78** [comment]
yes, let's just dump everything into each row.

**Comment by mdlincoln** [comment]
A fully-joined sales contents CSV is about 8 GB (839MB when gzipped) and 1259470 rows x 1222 cols.

I'd say either: 
1. Enable LFS (via GitHub-hosted LFS this'd probably require [purchasing a data pack](https://help.github.com/articles/about-storage-and-bandwidth-usage/))
2. Pick another venue for passing the data around
3. Start off with a subset, say 10k rows. Because not all STAR rows are independent observations, this would make it difficult testing things like multi-object transactions, multiple events over object lifetime, etc.

**Comment by joshuago78** [comment]
OK, I have purchased one data pack on Github, which gives us 50GB/month.

However, I think it would still be worthwhile to create a subset for use with unit testing.

**Comment by azaroth42** [comment]
Given this, is it worth revisiting the single CSV approach?

**Comment by mdlincoln** [comment]
@azaroth42 The somewhat-more-normalized-but-still-mostly-denormalized sales contents, descriptions, and authority tables exported directly from STAR come to about 3 GB, so it's smaller - but not by an order of magnitude.

I can work out a smaller ["snowball"](https://en.wikipedia.org/wiki/Snowball_sampling) sample that tries to at least pull in related rows so that we get a sample of complete cases - for definitions of complete case that we can currently recognize and capture.

**Comment by joshuago78** [comment]
@azaroth42 did you have a different plan in mind? At the moment I prefer the single CSV, because I can have Matt perform the necessary joins, which is easier than having my teams do it as they create the JSON docs. My team will get more familiar with the data as they work on the pipeline, but for now, Matt can simply work faster because he knows the data.

@mdlincoln I have created a separate repo (https://github.com/gri-is/pirdata) for storing the full data sets. Just put a sample set in this repo.

**Comment by mdlincoln** [comment]
- [x] Post full datasets to https://github.com/gri-is/pirdata
- [ ] Post sample sales contents data to this repo
- [ ] Post sample Knoedler data to repo
