### ISSUE TITLE
date scripts

### ISSUE THREAD

**Issue by melissaagill** [gri-is/lodjob#7]
convert dates for sale date and entry date in Knoedler to BotB + EotE

**Comment by azaroth42** [comment]
Output:
```
                  "timespan": {
                    "id": "http://data.getty.edu/provenance/TimeSpan/sale_span_K-2", 
                    "type": "TimeSpan", 
                    "begin_of_the_begin": "1878-09-04", 
                    "end_of_the_end": "1878-09-04"
                  } 
```

**Comment by joshuago78** [comment]
leave `id` empty for now

**Comment by mdlincoln** [comment]
This should handle the following cases:
- Year, month, day all present
````
"begin_of_the_begin": "YYYY-MM-DD", 
"end_of_the_end": "YYYY-MM-DD"
````
- Year, month present
````
"begin_of_the_begin": "YYYY-MM-01", 
"end_of_the_end": "YYYY-MM-XX" 
````
(XX should be largest valid day for that month/year combination. Leap years will affect this!)
- Year present
````
"begin_of_the_begin": "YYYY-01-01", 
"end_of_the_end": "YYYY-12-31"
````
- Year, day present; month missing: I think this should just error for now, so we can check original record for typos. There should be few if any cases of this.
- All missing: Return `NULL`? (@joshuago78 how do we want to assert that there should be no timespan for a record?)

Some edge cases:
- You _must_ test that these resulting dates are valid, as you may encounter entries that appear complete, but are invalid, e.g, `1901-02-29` is a leap year that does not have a February 29th. I think we should just increment these values down to make them valid.
- There may still be some records where the date is otherwise unparseable, e.g. `1691-21-05` (the month and day are transposed in the original export). For now, this should error until we fix it in the source.
